"""Generate the EasyBar widget package catalog from the widgets repository."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import re
import tomllib
from urllib.parse import urlparse


GENERATED_HEADER = """<!--
This file is generated by scripts/generate/widget_docs.py.
Do not edit it by hand. Update the package metadata or README in easybar-app/widgets instead.
-->

"""

MARKDOWN_LINK = re.compile(r"(!?)\[([^\]]*)\]\(([^)]+)\)")


@dataclass(frozen=True)
class Package:
    name: str
    version: str
    kind: str
    description: str
    license: str
    minimum_easybar_version: str
    categories: tuple[str, ...]
    dependencies: dict[str, str]
    exports: dict[str, str]
    requirements: dict[str, object]
    repository_url: str
    repository_path: str
    readme_title: str
    readme_body: str

    @property
    def source_url(self) -> str:
        return f"{self.repository_url}/tree/main/{self.repository_path}"


def required_string(manifest: dict[str, object], key: str, source: Path) -> str:
    value = manifest.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{source}: {key} must be a non-empty string")
    return value.strip()


def string_mapping(value: object, source: Path, key: str) -> dict[str, str]:
    if value is None:
        return {}
    if not isinstance(value, dict):
        raise ValueError(f"{source}: {key} must be a table")

    result: dict[str, str] = {}
    for item_key, item_value in value.items():
        if not isinstance(item_key, str) or not isinstance(item_value, str):
            raise ValueError(f"{source}: {key} entries must map strings to strings")
        result[item_key] = item_value
    return result


def string_sequence(value: object, source: Path, key: str) -> tuple[str, ...]:
    if value is None:
        return ()
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise ValueError(f"{source}: {key} must be an array of strings")
    return tuple(value)


def split_readme(readme: str, fallback_title: str) -> tuple[str, str]:
    lines = readme.replace("\r\n", "\n").replace("\r", "\n").splitlines()
    title = fallback_title

    if lines and lines[0].startswith("# "):
        title = lines.pop(0)[2:].strip() or fallback_title
        while lines and not lines[0].strip():
            lines.pop(0)

    body = "\n".join(lines).rstrip()
    return title, f"{body}\n" if body else ""


def is_relative_url(url: str) -> bool:
    stripped = url.strip()
    parsed = urlparse(stripped)
    return bool(stripped) and not parsed.scheme and not parsed.netloc and not stripped.startswith(
        ("#", "/")
    )


def rewrite_readme_links(body: str, package: Package) -> str:
    def replace(match: re.Match[str]) -> str:
        image_marker, label, destination = match.groups()
        destination_parts = destination.strip().split(maxsplit=1)
        url = destination_parts[0]
        suffix = f" {destination_parts[1]}" if len(destination_parts) == 2 else ""

        if not is_relative_url(url):
            return match.group(0)

        clean_url = url.removeprefix("./")
        if image_marker:
            base = "https://raw.githubusercontent.com/easybar-app/widgets/main"
        else:
            base = f"{package.repository_url}/blob/main"

        resolved = f"{base}/{package.repository_path}/{clean_url}{suffix}"
        return f"{image_marker}[{label}]({resolved})"

    return MARKDOWN_LINK.sub(replace, body)


def load_package(package_dir: Path) -> Package:
    manifest_path = package_dir / "package.toml"
    with manifest_path.open("rb") as manifest_file:
        manifest = tomllib.load(manifest_file)

    name = required_string(manifest, "name", manifest_path)
    if name != package_dir.name:
        raise ValueError(
            f"{manifest_path}: package name {name!r} must match directory {package_dir.name!r}"
        )

    repository = manifest.get("repository")
    if not isinstance(repository, dict):
        raise ValueError(f"{manifest_path}: repository must be a table")

    readme_name = required_string(manifest, "readme", manifest_path)
    readme_path = package_dir / readme_name
    if not readme_path.is_file():
        raise ValueError(f"{manifest_path}: README does not exist: {readme_path}")

    readme_title, readme_body = split_readme(
        readme_path.read_text(encoding="utf-8"), name
    )
    requirements = manifest.get("requirements", {})
    if not isinstance(requirements, dict):
        raise ValueError(f"{manifest_path}: requirements must be a table")

    return Package(
        name=name,
        version=required_string(manifest, "version", manifest_path),
        kind=required_string(manifest, "kind", manifest_path),
        description=required_string(manifest, "description", manifest_path),
        license=required_string(manifest, "license", manifest_path),
        minimum_easybar_version=required_string(
            manifest, "minimum_easybar_version", manifest_path
        ),
        categories=string_sequence(manifest.get("categories"), manifest_path, "categories"),
        dependencies=string_mapping(
            manifest.get("dependencies"), manifest_path, "dependencies"
        ),
        exports=string_mapping(manifest.get("exports"), manifest_path, "exports"),
        requirements=dict(requirements),
        repository_url=required_string(repository, "url", manifest_path),
        repository_path=required_string(repository, "path", manifest_path),
        readme_title=readme_title,
        readme_body=readme_body,
    )


def markdown_escape(value: str) -> str:
    return value.replace("|", "\\|")


def code_values(values: tuple[str, ...] | list[str]) -> str:
    return ", ".join(f"`{markdown_escape(value)}`" for value in values)


def render_index(packages: list[Package]) -> str:
    lines = [
        GENERATED_HEADER.rstrip(),
        "",
        "# Widget Package Catalog",
        "",
        "Official EasyBar widgets and Lua libraries are independently versioned in the",
        "[widgets repository](https://github.com/easybar-app/widgets). Search this site to find a",
        "package by name, integration, command, setting, or behavior.",
        "",
        "Install a widget by package name:",
        "",
        "```sh",
        "easybar widgets install PACKAGE",
        "```",
        "",
        '<div class="grid cards" markdown>',
        "",
    ]

    for package in packages:
        labels = " · ".join(
            [f"`{package.kind}`", f"`v{package.version}`", *[f"`{c}`" for c in package.categories]]
        )
        lines.extend(
            [
                f"-   **[`{package.name}`]({package.name}.md)**",
                "",
                f"    {labels}",
                "",
                "    ---",
                "",
                f"    {package.description}",
                "",
                f"    [Package details]({package.name}.md) · [Source]({package.source_url})",
                "",
            ]
        )

    lines.extend(
        [
            "</div>",
            "",
            "The registry is optional. You can also install a package from a local directory or",
            "archive; see [Widget Packages](../runtime/widget-packages.md).",
            "",
            "To add an official package, follow",
            "[Contributing an EasyBar Widget](../lua/guides/contributing-widget.md).",
            "",
        ]
    )
    return "\n".join(lines)


def dependency_links(package: Package, package_names: set[str]) -> str:
    values = []
    for dependency, constraint in sorted(package.dependencies.items()):
        label = (
            f"[`{dependency}`]({dependency}.md)"
            if dependency in package_names
            else f"`{dependency}`"
        )
        values.append(f"{label} `{markdown_escape(constraint)}`")
    return ", ".join(values) if values else "None"


def render_package(package: Package, package_names: set[str]) -> str:
    categories = code_values(list(package.categories)) or "None"
    lines = [
        GENERATED_HEADER.rstrip(),
        "",
        f"# {package.readme_title}",
        "",
        package.description,
        "",
    ]

    if package.kind == "widget":
        lines.extend(
            [
                "```sh",
                f"easybar widgets install {package.name}",
                "```",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "This is a library package. The package manager installs it when another package",
                "declares it as a dependency.",
                "",
            ]
        )

    lines.extend(
        [
            "| Package metadata | Value |",
            "| --- | --- |",
            f"| Name | `{package.name}` |",
            f"| Version | `{package.version}` |",
            f"| Kind | `{package.kind}` |",
            f"| Minimum EasyBar | `{package.minimum_easybar_version}` |",
            f"| License | `{package.license}` |",
            f"| Categories | {categories} |",
            f"| Dependencies | {dependency_links(package, package_names)} |",
        ]
    )

    commands = package.requirements.get("commands")
    if isinstance(commands, list) and all(isinstance(command, str) for command in commands):
        lines.append(f"| Required commands | {code_values(commands) or 'None'} |")

    environment = package.requirements.get("optional_environment")
    if isinstance(environment, list) and all(isinstance(item, str) for item in environment):
        lines.append(f"| Optional environment | {code_values(environment) or 'None'} |")

    if package.exports:
        exports = ", ".join(
            f"`{markdown_escape(name)}`" for name in sorted(package.exports)
        )
        lines.append(f"| Exported modules | {exports} |")

    if package.requirements.get("native_inbox") is True:
        lines.append("| Native inbox | Required |")

    lines.extend(
        [
            "",
            f"[View package source]({package.source_url})",
            "",
            "## Package documentation",
            "",
            rewrite_readme_links(package.readme_body, package).rstrip(),
            "",
        ]
    )
    return "\n".join(lines)


def generate(widgets_root: Path, output: Path) -> list[Path]:
    packages_root = widgets_root / "packages"
    if not packages_root.is_dir():
        raise ValueError(f"widgets packages directory does not exist: {packages_root}")

    package_dirs = sorted(
        path
        for path in packages_root.iterdir()
        if path.is_dir() and (path / "package.toml").is_file()
    )
    packages = [load_package(package_dir) for package_dir in package_dirs]
    if not packages:
        raise ValueError(f"no packages found in {packages_root}")

    names = [package.name for package in packages]
    if len(names) != len(set(names)):
        raise ValueError("package names must be unique")

    output.mkdir(parents=True, exist_ok=True)
    expected_names = {"index.md", *[f"{package.name}.md" for package in packages]}
    for existing in output.glob("*.md"):
        if existing.name not in expected_names:
            existing.unlink()

    written = []
    index_path = output / "index.md"
    index_path.write_text(render_index(packages), encoding="utf-8")
    written.append(index_path)

    package_names = set(names)
    for package in packages:
        package_path = output / f"{package.name}.md"
        package_path.write_text(render_package(package, package_names), encoding="utf-8")
        written.append(package_path)

    return written


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--widgets-root",
        type=Path,
        required=True,
        help="Path to the easybar-app/widgets checkout.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/content/packages"),
        help="Generated Markdown destination.",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    written = generate(args.widgets_root.resolve(), args.output.resolve())
    print(f"Generated {len(written)} widget catalog pages in {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
