import Foundation

/// Renders the generated Markdown reference for EasyBar's public configuration schema.
public enum ConfigReferenceRenderer {
  private enum CatalogValue: Encodable {
    case activeDefault(String)
    case example(String)

    func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .activeDefault:
        try container.encode("default")
      case .example:
        try container.encode("example")
      }
    }
  }

  private struct CatalogEntry: Encodable {
    let key: String
    let value: CatalogValue
    let description: String

    enum CodingKeys: String, CodingKey {
      case key
      case kind
      case value
      case description
    }

    func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(key, forKey: .key)
      try container.encode(value, forKey: .kind)
      switch value {
      case .activeDefault(let value), .example(let value):
        try container.encode(value, forKey: .value)
      }
      try container.encode(description, forKey: .description)
    }
  }

  private struct CatalogSection: Encodable {
    let name: String
    let entries: [CatalogEntry]
  }

  private struct Catalog: Encodable {
    let schemaVersion = 1
    let sections: [CatalogSection]
  }

  /// Returns the complete configuration reference as normalized Markdown.
  public static func render() -> String {
    var lines = [
      "<!--",
      "This file is generated by EasyBarGenerateConfig config-docs.",
      "Do not edit this file by hand. Update the EasyBarConfigSchema module sources instead.",
      "-->",
      "",
      "# Configuration Reference",
      "",
      "Generated from the `EasyBarConfigSchema` module: `ConfigSchema.swift` and the `ConfigSchema*Lines.swift` files.",
      "",
      "Use this page when you need the exact default value and short description for a supported config key.",
      "For concepts and usage examples, use the hand-written configuration guides.",
      "",
      "`Not set` means the shipped default config omits that key. The Example column shows a commented value that can be enabled explicitly; the description may also document a derived runtime fallback.",
      "",
    ]

    for section in documentedSections() {
      lines.append("## `\(section.name)`")
      lines.append("")
      lines.append("| Key | Default | Example | Description |")
      lines.append("| --- | ------- | ------- | ----------- |")

      for entry in section.entries {
        let description = markdownEscape(entry.description)
        let defaultValue: String
        let exampleValue: String

        switch entry.value {
        case .activeDefault(let value):
          defaultValue = code(markdownEscape(value))
          exampleValue = "—"
        case .example(let value):
          defaultValue = "Not set"
          exampleValue = code(markdownEscape(value))
        }

        lines.append(
          "| \(code(entry.key)) | \(defaultValue) | \(exampleValue) | \(description) |"
        )
      }

      lines.append("")
    }

    return lines.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines) + "\n"
  }

  /// Returns a stable JSON catalog that documentation tooling can render without Swift.
  public static func renderCatalog() throws -> String {
    let catalog = Catalog(
      sections: documentedSections().map { CatalogSection(name: $0.name, entries: $0.entries) }
    )
    let encoder = JSONEncoder()
    encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
    let data = try encoder.encode(catalog)
    guard let text = String(data: data, encoding: .utf8) else {
      throw EncodingError.invalidValue(
        catalog,
        EncodingError.Context(codingPath: [], debugDescription: "Could not encode UTF-8 JSON")
      )
    }
    return text + "\n"
  }

  private static func documentedSections() -> [(name: String, entries: [CatalogEntry])] {
    var result: [(name: String, entries: [CatalogEntry])] = []
    var currentName: String?
    var currentSectionIsCommented = false
    var currentSectionIsDocumented = false
    var currentEntries: [CatalogEntry] = []

    func flush() {
      guard let name = currentName, !currentEntries.isEmpty else { return }
      result.append((name, currentEntries))
      currentEntries.removeAll()
    }

    for line in ConfigSchemaRegistry.lines {
      switch line {
      case .section(let name, let commented, _, let documented):
        flush()
        currentName = name
        currentSectionIsCommented = commented
        currentSectionIsDocumented = documented

      case .entry(let key, let value, let description, let commented, _, let documented):
        guard currentSectionIsDocumented, documented else { continue }
        let catalogValue: CatalogValue =
          currentSectionIsCommented || commented ? .example(value) : .activeDefault(value)
        currentEntries.append(
          CatalogEntry(
            key: key,
            value: catalogValue,
            description: description
          ))

      case .optionalEntry(let key, let value, let description):
        guard currentSectionIsDocumented else { continue }
        currentEntries.append(
          CatalogEntry(
            key: key,
            value: .example(value),
            description: description
          ))

      case .blank, .comment:
        continue
      }
    }

    flush()
    return result
  }

  private static func markdownEscape(_ value: String) -> String {
    value.replacingOccurrences(of: "|", with: "\\|")
  }

  private static func code(_ value: String) -> String {
    "`\(value.replacingOccurrences(of: "`", with: "\\`"))`"
  }
}
